defmodule LongOrShort.Analysis do
  @moduledoc """
  Analysis domain — results of LLM-driven analyses of news articles
  and the broader market.

  Each analysis type is its own resource (no polymorphic JSON blobs)
  to keep Ash validations, queries, and policies first-class. Ships:

    * `NewsAnalysis` (LON-78 epic) — per-article, per-trader signal
      card with persona-tuned verdict.
    * `MorningBriefDigest` (LON-150) — shared, time-bucketed macro
      market brief regenerated by cron.

  Future analysis types (e.g. `PricePatternAnalysis`,
  `SynthesisAnalysis`) get their own resources alongside.
  """

  use Ash.Domain, otp_app: :long_or_short

  resources do
    resource LongOrShort.Analysis.NewsAnalysis do
      define :create_news_analysis, action: :create
      define :upsert_news_analysis, action: :upsert
      define :get_news_analysis, action: :read, get_by: [:id]

      define :get_news_analysis_by_article,
        action: :get_by_article,
        args: [:article_id],
        get?: true,
        not_found_error?: false

      define :list_recent_analyses, action: :recent
      define :destroy_news_analysis, action: :destroy
    end

    resource LongOrShort.Analysis.MorningBriefDigest do
      define :upsert_digest, action: :upsert

      # Page-load path: callers look up the brief for "today's
      # premarket" etc. `get?: true` returns nil instead of erroring
      # when the cron hasn't produced that slot yet — LiveView treats
      # nil as the "준비 중" fallback.
      define :get_digest,
        action: :get_by_slot,
        args: [:bucket_date, :bucket],
        get?: true,
        not_found_error?: false

      define :list_digests, action: :recent
    end
  end
end
