import Config
config :ash, policies: [show_policy_breakdowns?: true]

# Configure your database
config :long_or_short, LongOrShort.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "long_or_short_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  log: false

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :long_or_short, LongOrShortWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Fr6sEpLp4Lc055F5QBjo4dmfvFkabqiJD4UUjYXv2pG5FavpWL0TA2VwWfAOr2NU",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:long_or_short, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:long_or_short, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :long_or_short, LongOrShortWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/long_or_short_web/router\.ex$"E,
      ~r"lib/long_or_short_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :long_or_short, dev_routes: true, token_signing_secret: "+fIN1aPbO9affdnNiGKGP3NsLQNbfLxC"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# News ingestion sources for development. Dummy generates synthetic
# articles every 3 seconds for end-to-end pipeline validation.
#
# Finnhub and Alpaca play complementary roles, not redundant ones:
#
#   - Finnhub polls our tracked universe per-symbol — guarantees
#     deep, watchlist-scoped coverage of every ticker we explicitly
#     care about (3-day history per symbol).
#   - Alpaca (LON-128) is the market-wide firehose (no `symbols=`
#     filter) — catches catalysts on tickers we haven't added to
#     `priv/tracked_tickers.txt` yet (premarket movers, breakouts,
#     macro-driven sector news).
#
# Both stay on indefinitely. Dedup is per `(source, external_id,
# symbol)`, so the same catalyst landing in both feeds creates two
# Article rows — UI groups them by `external_id` / title hash if
# duplicate display becomes painful.
config :long_or_short,
  enabled_news_sources: [
    LongOrShort.News.Sources.Alpaca,
    LongOrShort.News.Sources.Finnhub,
    LongOrShort.News.Sources.SecEdgar
  ]

# Dilution-aware filings ingestion (LON-106 epic).
# Briefly enabled 2026-05-15 to gather a real-data baseline (1 batch =
# ~$0.21, ~82% Sonnet, 35% rejection rate — all higher than projected).
# Disabled pending LLM-cost optimization investigation:
#   1. Sonnet-vs-Haiku routing (why so much Sonnet?)
#   2. Prompt caching engagement (no measurable reduction)
#   3. Extraction rejection root cause (35% rejected/skipped)
# Re-enable by adding LongOrShort.Filings.Sources.SecEdgar back here.
config :long_or_short, :enabled_filing_sources, []
