defmodule LongOrShort.Repo.Migrations.AddSourceState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:source_states, primary_key: false) do
      add :source, :text, null: false, primary_key: true
      add :last_success_at, :utc_datetime_usec
      add :last_error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:source_states, [:source], name: "source_states_unique_source_index")
  end

  def down do
    drop_if_exists unique_index(:source_states, [:source],
                     name: "source_states_unique_source_index"
                   )

    drop table(:source_states)
  end
end
