defmodule LongOrShort.Repo.Migrations.CreateFilingAnalyses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:filing_analyses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :analyzed_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :dilution_type, :text, null: false
      add :deal_size_usd, :decimal
      add :share_count, :bigint
      add :pricing_method, :text, null: false
      add :pricing_discount_pct, :decimal
      add :warrant_strike, :decimal
      add :warrant_term_years, :bigint
      add :atm_remaining_shares, :bigint
      add :atm_total_authorized_shares, :bigint
      add :shelf_total_authorized_usd, :decimal
      add :shelf_remaining_usd, :decimal
      add :convertible_conversion_price, :decimal
      add :has_anti_dilution_clause, :boolean, default: false
      add :has_death_spiral_convertible, :boolean, default: false
      add :is_reverse_split_proxy, :boolean, default: false
      add :reverse_split_ratio, :text
      add :summary, :text
      add :dilution_severity, :text, null: false
      add :matched_rules, {:array, :text}, default: []
      add :severity_reason, :text
      add :extraction_quality, :text, null: false
      add :rejected_reason, :text
      add :flags, {:array, :text}, default: []
      add :provider, :text, null: false
      add :model, :text, null: false
      add :raw_response, :map

      add :filing_id,
          references(:filings,
            column: :id,
            name: "filing_analyses_filing_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ), null: false

      add :ticker_id,
          references(:tickers,
            column: :id,
            name: "filing_analyses_ticker_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ), null: false
    end

    create index(:filing_analyses, [:ticker_id, :dilution_severity],
             name: "filing_analyses_ticker_id_dilution_severity_index"
           )

    create unique_index(:filing_analyses, [:filing_id],
             name: "filing_analyses_unique_filing_analysis_index"
           )
  end

  def down do
    drop constraint(:filing_analyses, "filing_analyses_filing_id_fkey")

    drop constraint(:filing_analyses, "filing_analyses_ticker_id_fkey")

    drop_if_exists unique_index(:filing_analyses, [:filing_id],
                     name: "filing_analyses_unique_filing_analysis_index"
                   )

    drop_if_exists index(:filing_analyses, [:ticker_id, :dilution_severity],
                     name: "filing_analyses_ticker_id_dilution_severity_index"
                   )

    drop table(:filing_analyses)
  end
end
