defmodule LongOrShort.Repo.Migrations.AddArticles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:articles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :fetched_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source, :text, null: false
      add :external_id, :text, null: false
      add :title, :text, null: false
      add :summary, :text
      add :url, :text
      add :raw_category, :text
      add :sentiment, :text, default: "unknown"
      add :content_hash, :text
      add :published_at, :utc_datetime_usec, null: false

      add :ticker_id,
          references(:tickers,
            column: :id,
            name: "articles_ticker_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(:articles, [:source, :external_id, :ticker_id],
             name: "articles_unique_source_external_ticker_index"
           )

    create index(:articles, [:ticker_id, :published_at])
  end

  def down do
    drop index(:articles, [:ticker_id, :published_at])
    drop constraint(:articles, "articles_ticker_id_fkey")

    drop_if_exists unique_index(:articles, [:source, :external_id, :ticker_id],
                     name: "articles_unique_source_external_ticker_index"
                   )

    drop table(:articles)
  end
end
