defmodule LongOrShort.Repo.Migrations.AddArticlesRaw do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:articles_raw, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :fetched_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :raw_payload, :map, null: false

      add :article_id,
          references(:articles,
            column: :id,
            name: "articles_raw_article_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ), null: false
    end

    create unique_index(:articles_raw, [:article_id], name: "articles_raw_unique_article_index")
  end

  def down do
    drop constraint(:articles_raw, "articles_raw_article_id_fkey")

    drop_if_exists unique_index(:articles_raw, [:article_id],
                     name: "articles_raw_unique_article_index"
                   )

    drop table(:articles_raw)
  end
end
