defmodule LongOrShort.Repo.Migrations.AddSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :key, :text, null: false
      add :value, :text, null: false
      add :type, :text, null: false
      add :description, :text
      add :default_value, :text

      add :updated_by_id,
          references(:users,
            column: :id,
            name: "settings_updated_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create unique_index(:settings, [:key], name: "settings_unique_key_index")
  end

  def down do
    drop constraint(:settings, "settings_updated_by_id_fkey")

    drop_if_exists unique_index(:settings, [:key], name: "settings_unique_key_index")

    drop table(:settings)
  end
end
