defmodule LongOrShort.Repo.Migrations.AddInsiderTransactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:insider_transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :filer_name, :text
      add :filer_role, :text, null: false
      add :transaction_code, :text, null: false
      add :share_count, :bigint
      add :price, :decimal
      add :transaction_date, :date, null: false

      add :filing_id,
          references(:filings,
            column: :id,
            name: "insider_transactions_filing_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ), null: false

      add :ticker_id,
          references(:tickers,
            column: :id,
            name: "insider_transactions_ticker_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ), null: false
    end

    create index(:insider_transactions, [:ticker_id, :transaction_date],
             name: "insider_transactions_ticker_id_transaction_date_index"
           )
  end

  def down do
    drop constraint(:insider_transactions, "insider_transactions_filing_id_fkey")

    drop constraint(:insider_transactions, "insider_transactions_ticker_id_fkey")

    drop_if_exists index(:insider_transactions, [:ticker_id, :transaction_date],
                     name: "insider_transactions_ticker_id_transaction_date_index"
                   )

    drop table(:insider_transactions)
  end
end
