defmodule LongOrShort.Repo.Migrations.AddTradingNote do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:trading_notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :trading_date, :date, null: false
      add :body, :text, null: false, default: ""

      add :user_id,
          references(:users,
            column: :id,
            name: "trading_notes_user_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:trading_notes, [:user_id, :trading_date],
             name: "trading_notes_unique_note_per_day_index"
           )
  end

  def down do
    drop constraint(:trading_notes, "trading_notes_user_id_fkey")

    drop_if_exists unique_index(:trading_notes, [:user_id, :trading_date],
                     name: "trading_notes_unique_note_per_day_index"
                   )

    drop table(:trading_notes)
  end
end
