defmodule LongOrShort.Repo.Migrations.AddTickerBriefings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ticker_briefings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :symbol, :text, null: false
      add :narrative, :text, null: false
      add :structured, :map, default: %{}
      add :citations, {:array, :map}, null: false, default: []
      add :provider, :text, null: false
      add :model, :text, null: false
      add :usage, :map, null: false, default: %{}
      add :cached_until, :utc_datetime_usec, null: false
      add :trading_profile_snapshot, :map, null: false, default: %{}
      add :generated_at, :utc_datetime_usec, null: false

      add :ticker_id,
          references(:tickers, column: :id, name: "ticker_briefings_ticker_id_fkey", type: :uuid),
          null: false

      add :generated_for_user_id,
          references(:users,
            column: :id,
            name: "ticker_briefings_generated_for_user_id_fkey",
            type: :uuid
          ), null: false
    end

    create unique_index(:ticker_briefings, [:ticker_id, :generated_for_user_id],
             name: "ticker_briefings_unique_ticker_user_active_index"
           )
  end

  def down do
    drop constraint(:ticker_briefings, "ticker_briefings_ticker_id_fkey")

    drop constraint(:ticker_briefings, "ticker_briefings_generated_for_user_id_fkey")

    drop_if_exists unique_index(:ticker_briefings, [:ticker_id, :generated_for_user_id],
                     name: "ticker_briefings_unique_ticker_user_active_index"
                   )

    drop table(:ticker_briefings)
  end
end
