defmodule LongOrShort.Repo.Migrations.SplitFilingAnalysisTier1Tier2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:filing_analyses) do
      modify :dilution_severity, :text, null: true
      add :extracted_keywords, :map
    end
  end

  def down do
    alter table(:filing_analyses) do
      remove :extracted_keywords
      modify :dilution_severity, :text, null: false
    end
  end
end
