defmodule LongOrShort.Repo.Migrations.CreateMorningBriefDigests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:morning_brief_digests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bucket_date, :date, null: false
      add :bucket, :text, null: false
      add :content, :text, null: false
      add :citations, {:array, :map}, null: false, default: []
      add :llm_provider, :text, null: false
      add :llm_model, :text, null: false
      add :input_tokens, :bigint, null: false, default: 0
      add :output_tokens, :bigint, null: false, default: 0
      add :search_calls, :bigint, null: false, default: 0
      add :raw_response, :map
      add :generated_at, :utc_datetime_usec, null: false
    end

    create unique_index(:morning_brief_digests, [:bucket_date, :bucket],
             name: "morning_brief_digests_unique_slot_index"
           )
  end

  def down do
    drop_if_exists unique_index(:morning_brief_digests, [:bucket_date, :bucket],
                     name: "morning_brief_digests_unique_slot_index"
                   )

    drop table(:morning_brief_digests)
  end
end
