defmodule LongOrShort.Repo.Migrations.AddDilutionSnapshotToNewsAnalyses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:news_analyses) do
      add :raw_response, :map
      add :dilution_severity_at_analysis, :text, null: false, default: "unknown"
      add :dilution_flags_at_analysis, {:array, :text}, null: false, default: []
      add :dilution_summary_at_analysis, :text
    end
  end

  def down do
    alter table(:news_analyses) do
      remove :dilution_summary_at_analysis
      remove :dilution_flags_at_analysis
      remove :dilution_severity_at_analysis
      remove :raw_response
    end
  end
end
