defmodule LongOrShort.Repo.Migrations.AddFilings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:filings_raw, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :fetched_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :raw_text, :text, null: false
      add :content_hash, :text, null: false
      add :filing_id, :uuid, null: false
    end

    create unique_index(:filings_raw, [:filing_id], name: "filings_raw_unique_filing_index")

    create table(:filings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:filings_raw) do
      modify :filing_id,
             references(:filings,
               column: :id,
               name: "filings_raw_filing_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    alter table(:filings) do
      add :fetched_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source, :text, null: false
      add :filing_type, :text, null: false
      add :filing_subtype, :text
      add :external_id, :text, null: false
      add :filer_cik, :text, null: false
      add :filed_at, :utc_datetime_usec, null: false
      add :url, :text

      add :ticker_id,
          references(:tickers,
            column: :id,
            name: "filings_ticker_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ), null: false
    end

    create index(:filings, [:ticker_id, :filed_at], name: "filings_ticker_id_filed_at_index")

    create unique_index(:filings, [:source, :external_id, :ticker_id],
             name: "filings_unique_source_external_ticker_index"
           )
  end

  def down do
    drop constraint(:filings, "filings_ticker_id_fkey")

    drop_if_exists unique_index(:filings, [:source, :external_id, :ticker_id],
                     name: "filings_unique_source_external_ticker_index"
                   )

    drop_if_exists index(:filings, [:ticker_id, :filed_at],
                     name: "filings_ticker_id_filed_at_index"
                   )

    alter table(:filings) do
      remove :ticker_id
      remove :url
      remove :filed_at
      remove :filer_cik
      remove :external_id
      remove :filing_subtype
      remove :filing_type
      remove :source
      remove :updated_at
      remove :fetched_at
    end

    drop constraint(:filings_raw, "filings_raw_filing_id_fkey")

    alter table(:filings_raw) do
      modify :filing_id, :uuid
    end

    drop table(:filings)

    drop_if_exists unique_index(:filings_raw, [:filing_id],
                     name: "filings_raw_unique_filing_index"
                   )

    drop table(:filings_raw)
  end
end
