defmodule LongOrShort.Repo.Migrations.AddCikToTickers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickers) do
      add :cik, :text
    end

    create unique_index(:tickers, [:cik],
             name: "tickers_unique_cik_index",
             where: "(cik IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:tickers, [:cik], name: "tickers_unique_cik_index")

    alter table(:tickers) do
      remove :cik
    end
  end
end
