defmodule LongOrShort.Repo.Migrations.AddTickersAndUserRole do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :id, :uuid, default: fragment("uuidv7()")
      add :role, :text, null: false, default: "trader"
    end

    create table(:tickers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :symbol, :text, null: false
      add :company_name, :text
      add :exchange, :text
      add :sector, :text
      add :industry, :text
      add :float_shares, :bigint
      add :shares_outstanding, :bigint
      add :last_price, :decimal
      add :last_price_updated_at, :utc_datetime_usec
      add :avg_volume_30d, :bigint
      add :is_active, :boolean, null: false, default: true
    end

    create unique_index(:tickers, [:symbol], name: "tickers_unique_symbol_index")
  end

  def down do
    drop_if_exists unique_index(:tickers, [:symbol], name: "tickers_unique_symbol_index")

    drop table(:tickers)

    alter table(:users) do
      remove :role
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end
  end
end
