defmodule LongOrShort.Repo.Migrations.AddWatchlistItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:watchlist_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :notify?, :boolean, null: false, default: false

      add :user_id,
          references(:users,
            column: :id,
            name: "watchlist_items_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ), null: false

      add :ticker_id,
          references(:tickers,
            column: :id,
            name: "watchlist_items_ticker_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ), null: false
    end

    create unique_index(:watchlist_items, [:user_id, :ticker_id],
             name: "watchlist_items_unique_user_ticker_index"
           )
  end

  def down do
    drop constraint(:watchlist_items, "watchlist_items_user_id_fkey")

    drop constraint(:watchlist_items, "watchlist_items_ticker_id_fkey")

    drop_if_exists unique_index(:watchlist_items, [:user_id, :ticker_id],
                     name: "watchlist_items_unique_user_ticker_index"
                   )

    drop table(:watchlist_items)
  end
end
