defmodule LongOrShort.Repo.Migrations.AddRepetitionAnalyses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:repetition_analysis, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :is_repetition, :boolean
      add :theme, :text
      add :repetition_count, :bigint, null: false, default: 1
      add :related_article_ids, {:array, :uuid}, default: []
      add :fatigue_level, :text
      add :reasoning, :text
      add :model_used, :text
      add :tokens_used_input, :bigint
      add :tokens_used_output, :bigint
      add :status, :text, null: false, default: "pending"
      add :error_message, :text

      add :article_id,
          references(:articles,
            column: :id,
            name: "repetition_analysis_article_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ), null: false
    end

    create index(:repetition_analysis, [:article_id, :status])

    create index(:repetition_analysis, [:fatigue_level])

    create index(:repetition_analysis, [:article_id])
  end

  def down do
    drop constraint(:repetition_analysis, "repetition_analysis_article_id_fkey")

    drop_if_exists index(:repetition_analysis, [:article_id])

    drop_if_exists index(:repetition_analysis, [:fatigue_level])

    drop_if_exists index(:repetition_analysis, [:article_id, :status])

    drop table(:repetition_analysis)
  end
end
