defmodule LongOrShort.Repo.Migrations.AddTradingPlaybookAndCheckState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:trading_playbooks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :kind, :text, null: false
      add :name, :text, null: false
      add :items, {:array, :map}, null: false, default: []
      add :version, :bigint, null: false, default: 1
      add :active, :boolean, null: false, default: true

      add :user_id,
          references(:users,
            column: :id,
            name: "trading_playbooks_user_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:trading_playbooks, [:user_id, :kind, :name, :version],
             name: "trading_playbooks_unique_version_in_chain_index"
           )

    create table(:trading_playbook_check_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :trading_date, :date, null: false
      add :checked_items, :map, null: false, default: %{}

      add :user_id,
          references(:users,
            column: :id,
            name: "trading_playbook_check_states_user_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :playbook_id,
          references(:trading_playbooks,
            column: :id,
            name: "trading_playbook_check_states_playbook_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:trading_playbook_check_states, [:user_id, :playbook_id, :trading_date],
             name: "trading_playbook_check_states_unique_check_state_per_day_index"
           )
  end

  def down do
    drop constraint(:trading_playbook_check_states, "trading_playbook_check_states_user_id_fkey")

    drop constraint(
           :trading_playbook_check_states,
           "trading_playbook_check_states_playbook_id_fkey"
         )

    drop_if_exists unique_index(
                     :trading_playbook_check_states,
                     [:user_id, :playbook_id, :trading_date],
                     name: "trading_playbook_check_states_unique_check_state_per_day_index"
                   )

    drop table(:trading_playbook_check_states)

    drop constraint(:trading_playbooks, "trading_playbooks_user_id_fkey")

    drop_if_exists unique_index(:trading_playbooks, [:user_id, :kind, :name, :version],
                     name: "trading_playbooks_unique_version_in_chain_index"
                   )

    drop table(:trading_playbooks)
  end
end
