defmodule LongOrShort.Repo.Migrations.AddMomentumAnalysis do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:momentum_analyses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :analyzed_at, :utc_datetime_usec, null: false
      add :catalyst_strength, :text, null: false
      add :catalyst_type, :text, null: false
      add :sentiment, :text, null: false
      add :pump_fade_risk, :text, null: false, default: "insufficient_data"
      add :repetition_count, :bigint, null: false, default: 1
      add :repetition_summary, :text
      add :strategy_match, :text, null: false, default: "partial"
      add :verdict, :text, null: false
      add :headline_takeaway, :text, null: false
      add :detail_summary, :text
      add :detail_positives, :text
      add :detail_concerns, :text
      add :detail_checklist, :text
      add :detail_recommendation, :text
      add :price_at_analysis, :decimal
      add :float_shares_at_analysis, :bigint
      add :rvol_at_analysis, :float
      add :strategy_match_reasons, :map
      add :llm_provider, :text, null: false
      add :llm_model, :text, null: false
      add :input_tokens, :bigint
      add :output_tokens, :bigint

      add :article_id,
          references(:articles,
            column: :id,
            name: "momentum_analyses_article_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ), null: false
    end

    create unique_index(:momentum_analyses, [:article_id],
             name: "momentum_analyses_unique_article_index"
           )
  end

  def down do
    drop constraint(:momentum_analyses, "momentum_analyses_article_id_fkey")

    drop_if_exists unique_index(:momentum_analyses, [:article_id],
                     name: "momentum_analyses_unique_article_index"
                   )

    drop table(:momentum_analyses)
  end
end
