defmodule LongOrShort.Repo.Migrations.AddSmallCapUniverseMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:small_cap_universe_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :source, :text, null: false
      add :first_seen_at, :utc_datetime_usec, null: false
      add :last_seen_at, :utc_datetime_usec, null: false
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :ticker_id,
          references(:tickers,
            column: :id,
            name: "small_cap_universe_memberships_ticker_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:small_cap_universe_memberships, [:ticker_id, :source],
             name: "small_cap_universe_memberships_unique_ticker_source_index"
           )
  end

  def down do
    drop constraint(
           :small_cap_universe_memberships,
           "small_cap_universe_memberships_ticker_id_fkey"
         )

    drop_if_exists unique_index(:small_cap_universe_memberships, [:ticker_id, :source],
                     name: "small_cap_universe_memberships_unique_ticker_source_index"
                   )

    drop table(:small_cap_universe_memberships)
  end
end
