defmodule LongOrShort.Repo.Migrations.AddUserProfiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :full_name, :text
      add :phone, :text
      add :avatar_url, :text

      add :user_id,
          references(:users,
            column: :id,
            name: "user_profiles_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ), null: false
    end

    create unique_index(:user_profiles, [:user_id], name: "user_profiles_unique_user_index")
  end

  def down do
    drop constraint(:user_profiles, "user_profiles_user_id_fkey")

    drop_if_exists unique_index(:user_profiles, [:user_id],
                     name: "user_profiles_unique_user_index"
                   )

    drop table(:user_profiles)
  end
end
