defmodule LongOrShort.Repo.Migrations.AddArticlesTickerPublishedAtIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:articles, [:ticker_id, :published_at], name: "articles_ticker_published_at_idx")
  end

  def down do
    drop_if_exists index(:articles, [:ticker_id, :published_at],
                     name: "articles_ticker_published_at_idx"
                   )
  end
end
