defmodule LongOrShort.Repo.Migrations.AddPlaybookSnapshotToTickerBriefings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ticker_briefings) do
      add :playbook_snapshot, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:ticker_briefings) do
      remove :playbook_snapshot
    end
  end
end
