defmodule LongOrShort.Repo.Migrations.AddTradingProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:trading_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :trading_style, :text, null: false
      add :time_horizon, :text, null: false
      add :market_cap_focuses, {:array, :text}, null: false, default: []
      add :catalyst_preferences, {:array, :text}, null: false, default: []
      add :notes, :text
      add :price_min, :decimal
      add :price_max, :decimal
      add :float_max, :bigint

      add :user_id,
          references(:users,
            column: :id,
            name: "trading_profiles_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ), null: false
    end

    create unique_index(:trading_profiles, [:user_id], name: "trading_profiles_unique_user_index")
  end

  def down do
    drop constraint(:trading_profiles, "trading_profiles_user_id_fkey")

    drop_if_exists unique_index(:trading_profiles, [:user_id],
                     name: "trading_profiles_unique_user_index"
                   )

    drop table(:trading_profiles)
  end
end
