defmodule LongOrShort.Analysis.MorningBriefDigest do
  @moduledoc """
  Time-bucketed market brief — output of `LongOrShort.MorningBrief.Generator`
  (LON-151). Shared across all traders: one row per `(bucket_date, bucket)`
  slot, regenerated by cron at fixed ET times (LON-147).

  ## Why shared (not per-user)

  The brief is macro market commentary (CPI/NFP/Fed/index moves/sector
  flow) — not personalized trading advice. Traders apply their own
  strategy lens at read time. Ticker-specific persona work continues to
  live in `NewsAnalysis`, where it earns its keep.

  Schema therefore omits `user_id` / `trader_profile_snapshot`: there is
  exactly one canonical brief per slot, served to everyone.

  ## Lifecycle

  Cron triggers `Generator.generate_for_bucket(bucket)` at 05:00 /
  08:45 / 10:15 ET. Each run upserts the row under
  `(bucket_date, bucket)`, overwriting any prior content for that slot.
  No revision history — most-recent generation wins. `raw_response`
  preserves the full LLM response for audit, re-render, and cost
  calibration.

  ## Policies

  Authenticated trader users can read (market brief is shared content,
  not actor-scoped). SystemActor (cron) is the only writer. LON-15 will
  generalize the bypass shape.
  """

  use Ash.Resource,
    otp_app: :long_or_short,
    domain: LongOrShort.Analysis,
    data_layer: AshPostgres.DataLayer,
    authorizers: [Ash.Policy.Authorizer]

  postgres do
    table "morning_brief_digests"
    repo LongOrShort.Repo
  end

  identities do
    identity :unique_slot, [:bucket_date, :bucket]
  end

  attributes do
    uuid_v7_primary_key :id
    create_timestamp :created_at
    update_timestamp :updated_at

    attribute :bucket_date, :date do
      allow_nil? false
      public? true
      description "ET calendar date the brief covers."
    end

    attribute :bucket, :atom do
      allow_nil? false
      public? true
      constraints one_of: [:overnight, :premarket, :after_open]

      description """
      Trading-session bucket. Three values — narrower than the five
      buckets used for article classification (`Bucket.bucket_for/2`).
      `:after_open` here covers what article-side calls
      `:opening + :regular` (one daily 10:15 ET brief, not minute-level).
      """
    end

    attribute :content, :string do
      allow_nil? false
      public? true
      description "Markdown narrative produced by the LLM."
    end

    attribute :citations, {:array, :map} do
      allow_nil? false
      public? true
      default []

      description """
      Deduped, sequentially indexed citations. Each entry:
      `%{idx, url, title, source, cited_text, accessed_at}`.
      Provider-specific extraction (e.g. Anthropic's
      `web_search_result_location` → these keys) lives in the
      provider module (LON-150 `Providers.Claude.call_with_search/3`).
      """
    end

    attribute :llm_provider, :atom do
      allow_nil? false
      public? true
      # `:qwen_native` is reserved here even though LON-148 has yet to
      # ship — keeping it in the enum avoids a schema migration when
      # the Qwen fallback path lands.
      constraints one_of: [:anthropic, :qwen_native]
      description "Provider used for this generation."
    end

    attribute :llm_model, :string do
      allow_nil? false
      public? true
      description ~s(Model id, e.g. `"claude-haiku-4-5-20251001"`.)
    end

    attribute :input_tokens, :integer do
      allow_nil? false
      public? true
      default 0
    end

    attribute :output_tokens, :integer do
      allow_nil? false
      public? true
      default 0
    end

    attribute :search_calls, :integer do
      allow_nil? false
      public? true
      default 0
      description "Number of web_search tool invocations during this generation."
    end

    attribute :raw_response, :map do
      public? true

      description """
      Full provider response — content blocks, usage, etc. Kept for
      audit / re-render / cost calibration. Nullable because some
      future provider paths (or test fixtures) may not populate it.
      """
    end

    attribute :generated_at, :utc_datetime_usec do
      allow_nil? false
      public? true
      description "Wall-clock time the generation completed; advances on each cron run."
    end
  end

  @fields [
    :bucket_date,
    :bucket,
    :content,
    :citations,
    :llm_provider,
    :llm_model,
    :input_tokens,
    :output_tokens,
    :search_calls,
    :raw_response
  ]

  actions do
    defaults [:read, :destroy]

    create :create do
      primary? true
      accept @fields
      change set_attribute(:generated_at, &DateTime.utc_now/0)
    end

    create :upsert do
      upsert? true
      upsert_identity :unique_slot
      accept @fields

      upsert_fields [
        :content,
        :citations,
        :llm_provider,
        :llm_model,
        :input_tokens,
        :output_tokens,
        :search_calls,
        :raw_response,
        :generated_at
      ]

      change set_attribute(:generated_at, &DateTime.utc_now/0)
    end

    read :get_by_slot do
      get? true
      argument :bucket_date, :date, allow_nil?: false
      argument :bucket, :atom, allow_nil?: false
      filter expr(bucket_date == ^arg(:bucket_date) and bucket == ^arg(:bucket))
    end

    read :recent do
      description "Recent digests across all buckets — monitoring / audit / cost dashboard."
      pagination keyset?: true, required?: false, default_limit: 30
      prepare build(sort: [id: :desc])
    end
  end

  policies do
    bypass actor_attribute_equals(:system?, true) do
      authorize_if always()
    end

    bypass actor_attribute_equals(:role, :admin) do
      authorize_if always()
    end

    # Reads require any authenticated actor (no per-user scoping —
    # the brief is shared content). Writes are bypassed above for
    # SystemActor only, so traders cannot create/upsert from the web
    # layer.
    policy action_type(:read) do
      authorize_if actor_present()
    end
  end
end
